"""add email to doctors

Revision ID: 52d4d4429549
Revises: 8eeb76954e48
Create Date: 2026-02-01 21:09:11.592878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52d4d4429549'
down_revision: Union[str, Sequence[str], None] = '8eeb76954e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.add_column('doctors', sa.Column('specialty_id', sa.Integer(), nullable=False))
    op.add_column('doctors', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.drop_constraint(op.f('doctors_ibfk_1'), 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'specialties', ['specialty_id'], ['id'])
    op.drop_column('doctors', 'speciality_id')
    op.create_index(op.f('ix_specialties_uuid'), 'specialties', ['uuid'], unique=True)
    op.create_unique_constraint(None, 'specialties', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialties', type_='unique')
    op.drop_index(op.f('ix_specialties_uuid'), table_name='specialties')
    op.add_column('doctors', sa.Column('speciality_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key(op.f('doctors_ibfk_1'), 'doctors', 'specialties', ['speciality_id'], ['id'])
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'specialty_id')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.alter_column('appointments', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
