"""patients created

Revision ID: 6911a0f4dee9
Revises: 55f30a6ab754
Create Date: 2026-02-01 21:32:55.302764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6911a0f4dee9'
down_revision: Union[str, Sequence[str], None] = '55f30a6ab754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_lastname', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
