"""Medication and Prescription tables added, made changes with relationships and fields

Revision ID: b8245df7bd5e
Revises: c6df8eb5f934
Create Date: 2026-02-22 19:04:09.955344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8245df7bd5e'
down_revision: Union[str, Sequence[str], None] = 'c6df8eb5f934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.String(length=500), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_prescriptions_uuid'), 'prescriptions', ['uuid'], unique=True)
    op.create_table('medications',
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency_hours', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('notifications_enabled', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_uuid'), 'medications', ['uuid'], unique=True)
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('doctors', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.add_column('doctors', sa.Column('id_card_url', sa.String(length=500), nullable=True))
    op.add_column('doctors', sa.Column('license_url', sa.String(length=500), nullable=True))
    op.add_column('doctors', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('doctors', sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.add_column('doctors', sa.Column('is_verified', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.alter_column('doctors', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
    op.alter_column('doctors', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
    op.create_unique_constraint(None, 'doctors', ['license_number'])
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('patients', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('gender', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', name='genderenum'), nullable=False))
    op.add_column('patients', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('patients', sa.Column('blood_type', sa.String(length=5), nullable=True))
    op.alter_column('patients', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
    op.alter_column('patients', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
    op.create_unique_constraint(None, 'patients', ['email'])
    op.add_column('specialties', sa.Column('icon_url', sa.String(length=500), nullable=True))
    op.add_column('specialties', sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialties', 'is_active')
    op.drop_column('specialties', 'icon_url')
    op.drop_constraint(None, 'patients', type_='unique')
    op.alter_column('patients', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
    op.alter_column('patients', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
    op.drop_column('patients', 'blood_type')
    op.drop_column('patients', 'birth_date')
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'email')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.alter_column('doctors', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
    op.alter_column('doctors', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
    op.drop_column('doctors', 'is_verified')
    op.drop_column('doctors', 'is_active')
    op.drop_column('doctors', 'bio')
    op.drop_column('doctors', 'license_url')
    op.drop_column('doctors', 'id_card_url')
    op.drop_column('doctors', 'license_number')
    op.drop_column('appointments', 'updated_at')
    op.drop_index(op.f('ix_medications_uuid'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_prescriptions_uuid'), table_name='prescriptions')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
