"""Renaming columns in models

Revision ID: c6df8eb5f934
Revises: f15345037e0e
Create Date: 2026-02-21 18:35:38.876993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6df8eb5f934'
down_revision: Union[str, Sequence[str], None] = 'f15345037e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'doctor_name', new_column_name='first_name', existing_type=sa.String(length=255))
    op.alter_column('doctors', 'doctor_lastname', new_column_name='last_name', existing_type=sa.String(length=255))

    # --- 2. SECCIÓN CITAS (APPOINTMENTS) ---
    # Aquí sí añadimos la llave foránea al paciente
    op.add_column('appointments', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    
    # Borramos los nombres de texto en citas (esto está bien, porque ahora usaremos la relación)
    op.drop_column('appointments', 'patient_lastname')
    op.drop_column('appointments', 'patient_name')

    # --- 3. SECCIÓN PACIENTES ---
    # Si la tabla 'patients' ya existía con patient_name, cámbialos:
    op.alter_column('patients', 'patient_name', new_column_name='first_name', existing_type=sa.String(length=255))
    op.alter_column('patients', 'patient_lastname', new_column_name='last_name', existing_type=sa.String(length=255))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'first_name', new_column_name='patient_name', existing_type=sa.String(length=255))
    op.alter_column('patients', 'last_name', new_column_name='patient_lastname', existing_type=sa.String(length=255))

    # --- 2. SECCIÓN DOCTORES: VOLVER A NOMBRES ANTERIORES ---
    op.alter_column('doctors', 'first_name', new_column_name='doctor_name', existing_type=sa.String(length=255))
    op.alter_column('doctors', 'last_name', new_column_name='doctor_lastname', existing_type=sa.String(length=255))

    # --- 3. SECCIÓN CITAS (APPOINTMENTS) ---
    # Volvemos a crear las columnas de texto que borramos
    op.add_column('appointments', sa.Column('patient_name', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('patient_lastname', sa.String(length=255), nullable=True))
    
    # Quitamos la relación con la tabla de pacientes
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_column('appointments', 'patient_id')
    # ### end Alembic commands ###
